# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]{4}/[0-9]{2}$')])),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$')])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}')])),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('distance', models.IntegerField(default=0)),
                ('keam', models.IntegerField(default=0)),
                ('plus2', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('category', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
            ],
        ),
    ]
