# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='1234/17', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='The format for admission number is 1234/17', regex='^[0-9]{4}/[0-9]{2}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid pincode', regex='^[0-9]{6}$')])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid mobile number', regex='[0-9]{10}')])),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('item1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item4', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MessCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mess_cut_dates', models.CharField(max_length=100000)),
                ('approved_dates', models.CharField(default='{}', max_length=100000)),
                ('rejected_dates', models.CharField(default='{}', max_length=100000)),
                ('applied_date', models.CharField(max_length=100000, null=True)),
                ('process_date', models.CharField(max_length=100000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(default='1234/17', max_length=7)),
                ('fname', models.CharField(default='Name', max_length=100)),
                ('lname', models.CharField(default='Last_Name', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('room_number', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid mobile number', regex='[0-9]{10}')])),
            ],
        ),
    ]
