# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='plus2',
            new_name='plus_2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dob',
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_number',
            field=models.CharField(help_text='9999/17', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]{4}/[0-9]{2}$')]),
        ),
    ]
