# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0002_auto_20171225_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='room_no',
            new_name='room_number',
        ),
    ]
