# Generated by Django 2.0 on 2018-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0005_auto_20171230_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='application',
            name='religion',
        ),
        migrations.AlterField(
            model_name='expense',
            name='item1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Supplyco'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Meat'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fish'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Others'),
        ),
    ]
