# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0005_expense_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='month',
            new_name='date',
        ),
    ]
