# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0006_auto_20171105_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
