# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0008_auto_20171106_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_number',
            field=models.CharField(default='1234/17', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_mail',
            field=models.CharField(default='E-mail', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
