# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0008_auto_20171106_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cut_date', models.CharField(max_length=500000)),
            ],
        ),
    ]
