# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0009_messcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='cut_date',
            field=models.CharField(max_length=500000, verbose_name='Mess Cut'),
        ),
    ]
