# Generated by Django 2.0 on 2017-12-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0009_auto_20171123_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='application',
            name='keam',
        ),
        migrations.RemoveField(
            model_name='application',
            name='plus_2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
