# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0010_auto_20171123_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messcut',
            old_name='cut_date',
            new_name='mess_cut_dates',
        ),
    ]
