# Generated by Django 2.0 on 2017-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0010_auto_20171220_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='e_mail',
            field=models.CharField(default='E-mail', max_length=100),
        ),
    ]
