# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0011_auto_20171123_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
