# Generated by Django 2.0 on 2017-12-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0011_application_e_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='First_Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='Last_Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='e_mail',
            field=models.CharField(max_length=100),
        ),
    ]
