# Generated by Django 2.0 on 2017-12-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0012_auto_20171220_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='e_mail',
            new_name='email',
        ),
    ]
