# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0012_auto_20171123_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messcut',
            name='mess_cut_dates',
        ),
        migrations.AddField(
            model_name='messcut',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messcut',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 17, 31, 8, 930953, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
