# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0013_auto_20171123_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messcut',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='messcut',
            name='start_date',
        ),
        migrations.AddField(
            model_name='messcut',
            name='mess_cut_dates',
            field=models.CharField(default=datetime.datetime(2017, 11, 23, 17, 44, 55, 820681, tzinfo=utc), max_length=100000),
            preserve_default=False,
        ),
    ]
