# Generated by Django 2.0 on 2017-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0013_auto_20171220_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='room_no',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
