# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0014_auto_20171123_2314'),
        ('mhsite', '0009_auto_20171123_2222'),
    ]

    operations = [
    ]
