# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0016_auto_20171219_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
