# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0017_auto_20171219_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcut',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='messcut',
            name='mess_cut_dates',
            field=models.CharField(max_length=100000),
        ),
    ]
