# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 07:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0018_auto_20171219_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='e_mail',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid mobile number', regex='[0-9]{10}')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
    ]
