# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0019_auto_20171219_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='messcut',
            name='applied_date',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='messcut',
            name='approved_dates',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messcut',
            name='process_date',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='messcut',
            name='rejected_dates',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
    ]
