# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0020_auto_20171220_1313'),
        ('mhsite', '0016_auto_20171219_0641'),
    ]

    operations = [
    ]
