# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhsite', '0021_merge_20171223_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messcut',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='messcut',
            name='approved_dates',
            field=models.CharField(default='{}', max_length=100000),
        ),
        migrations.AlterField(
            model_name='messcut',
            name='rejected_dates',
            field=models.CharField(default='{}', max_length=100000),
        ),
    ]
